services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        container_name: lab_frontend
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            NEXT_PUBLIC_API_URL: http://localhost:3001
        depends_on: []
